### ISSUE TITLE
Exception in transformations from Component Diagrams to Fault Trees

### ISSUE THREAD

**Issue by maborjan** [CoWolf/CoWolf#344]
Steps to reproduce
- Create a component diagram
- Create a fault tree diagram
- Add a Software Component  "sc" to component diagram
- Add three Component Instances, type "sc" to component diagram
- Add a sub-component to any of the three component instances, type "sc"
- Co-Evolve component diagram to fault tree

``````
Syncing models...

!ENTRY org.eclipse.core.jobs 4 2 2014-09-18 16:49:36.615
!MESSAGE An internal error occurred during: "Coevolution of models".
!STACK 0
org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=4, size=4
    at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346)
    at org.eclipse.emf.ecore.util.EContentsEList$FeatureIteratorImpl.hasNext(EContentsEList.java:514)
    at org.eclipse.emf.ecore.util.EContentsEList$FeatureIteratorImpl.next(EContentsEList.java:595)
    at de.unistuttgart.ensure.transformations.util.TransformationsUtil.getFaultTreeInstanceModel(TransformationsUtil.java:222)
    at de.uni_stuttgart.iste.cowolf.transformation.component_diagram_fault_tree.ChangeTree.run(ChangeTree.java:737)
    at de.uni_stuttgart.iste.cowolf.transformation.component_diagram_fault_tree.ComponentDiagramFaultTreeTransformationManager.runTransformation(ComponentDiagramFaultTreeTransformationManager.java:114)
    at de.uni_stuttgart.iste.cowolf.transformation.AbstractTransformationManager.transform(AbstractTransformationManager.java:242)
    at de.uni_stuttgart.iste.cowolf.ui.transformation.handler.Transform$1.run(Transform.java:95)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)```
``````

**Comment by equiFX** [comment]
can't reproduce. the following instance did work on my computer:
![instance](https://cloud.githubusercontent.com/assets/7500105/4331658/be3a63b0-3fc8-11e4-8127-96d4e24c63a0.png)
