### ISSUE TITLE
NPE: Evolution and Show differences for model in Java Project

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#411]
Create a Java Project
-> Create a ctmc
-> Show differences of them or show the Evolution

**Comment by timsanwald** [comment]
Caused by: java.lang.NullPointerException
    at de.uni_stuttgart.iste.cowolf.ui.evolution.handlers.Evolution.execute(Evolution.java:59)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
