### ISSUE TITLE
Sequencediagram_LQN.hensin not found

### ISSUE THREAD

**Issue by jonasscheurich** [CoWolf/CoWolf#456]

**Comment by jonasscheurich** [comment]
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.FileNotFoundException: /rules/Sequencediagram_LQN.henshin
    at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
    at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
    at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:406)
    at org.eclipse.emf.henshin.model.resource.HenshinResourceSet.getModule(HenshinResourceSet.java:263)
    at de.uni_stuttgart.iste.cowolf.transformation.AbstractTransformationManager.runDiffsetTransformation(AbstractTransformationManager.java:303)
    at de.uni_stuttgart.iste.cowolf.transformation.AbstractTransformationManager.runTransformation(AbstractTransformationManager.java:264)
    at de.uni_stuttgart.iste.cowolf.transformation.AbstractTransformationManager.transform(AbstractTransformationManager.java:248)
    at de.uni_stuttgart.iste.cowolf.ui.transformation.handler.Transform$1.run(Transform.java:126)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.io.FileNotFoundException: /rules/Sequencediagram_LQN.henshin
    at org.eclipse.osgi.storage.url.bundleentry.Handler.findBundleEntry(Handler.java:37)
    at org.eclipse.osgi.storage.url.BundleResourceHandler.openConnection(BundleResourceHandler.java:169)
    at java.net.URL.openConnection(Unknown Source)
    at org.eclipse.core.internal.boot.PlatformURLConnection.connect(PlatformURLConnection.java:110)
    at org.eclipse.core.internal.boot.PlatformURLConnection.connect(PlatformURLConnection.java:91)
    at org.eclipse.core.internal.boot.PlatformURLConnection.getInputStream(PlatformURLConnection.java:229)
    at org.eclipse.emf.ecore.resource.impl.URIHandlerImpl.createInputStream(URIHandlerImpl.java:207)
    at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:360)
    at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1269)
    at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
    at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
    ... 7 more

**Comment by renetrefft** [comment]
Already fixed in master.
