### ISSUE TITLE
No results for DTMC analyze

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#458]
No analysis results. Problem with empty name in State, not ""

Same in CTMC

**Comment by philippniethammer** [comment]
Confirmed.
Error:

```
java.lang.NullPointerException: null
        at de.uni_stuttgart.iste.cowolf.model.dtmc.analyze.PRISMGenerator.compilePM(PRISMGenerator.java:269) ~[na:na]
        at de.uni_stuttgart.iste.cowolf.model.dtmc.analyze.PRISMGenerator.generatePM(PRISMGenerator.java:54) ~[na:na]
        at de.uni_stuttgart.iste.cowolf.model.dtmc.analyze.DTMCAnalyzeJob.run(DTMCAnalyzeJob.java:126) ~[na:na]
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54) [org.eclipse.core.jobs_3.6.0.v20140424-0053.jar:na]
```
