### ISSUE TITLE
Show differences throws error after Co-Evolution

### ISSUE THREAD

**Issue by muellerml** [CoWolf/CoWolf#481]
1. Create DTMC model
2. Co-Evolve with CTMC model
3. Select initial version of CTMC as base version, target version is still current version.

NullPointerException is thrown:
java.lang.NullPointerException
    at org.sidiff.difference.asymmetric.paramretrieval.ParameterMapper.mapParameters(ParameterMapper.java:71)
    at org.sidiff.difference.asymmetric.facade.AsymmetricDiffFacade.liftMeUp(AsymmetricDiffFacade.java:171)
    at de.uni_stuttgart.iste.cowolf.evolution.AbstractEvolutionManager.getDiff(AbstractEvolutionManager.java:118)
    at de.uni_stuttgart.iste.cowolf.ui.evolution.handlers.Evolve$1.run(Evolve.java:111)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by zimmerml** [comment]
similar problem with fault tree: #489

**Comment by timsanwald** [comment]
Can't reproduce this problem, just the #489

**Comment by timsanwald** [comment]
invalid see #489 instead
