### ISSUE TITLE
Show differences of a fault tree throws error 

### ISSUE THREAD

**Issue by zimmerml** [CoWolf/CoWolf#489]
1. Create a fault tree with a Hazard with an And-Gate as Input Gate which has two Basic Events as Input Events.
2. Select initial version of fault tree as base version, target version is still current version

(similar problem: #481)

NullPointerException is thrown:
java.lang.NullPointerException
at org.sidiff.difference.asymmetric.paramretrieval.ParameterMapper.mapParameters(ParameterMapper.java:71)
at org.sidiff.difference.asymmetric.facade.AsymmetricDiffFacade.liftMeUp(AsymmetricDiffFacade.java:171)
at de.uni_stuttgart.iste.cowolf.evolution.AbstractEvolutionManager.getDiff(AbstractEvolutionManager.java:118)
at de.uni_stuttgart.iste.cowolf.ui.evolution.handlers.Evolve$1.run(Evolve.java:111)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by timsanwald** [comment]
Looks like initial validation returns incorrect of base version because of missing hazard
