### ISSUE TITLE
LQN Evolution not working

### ISSUE THREAD

**Issue by philippniethammer** [CoWolf/CoWolf#507]
LQN Evolution is disabled since it always throws an error.

Errorlog:

```
java.lang.NullPointerException
    at org.sidiff.difference.technical.ResourceSetAdapter.addCorrespondenceB(ResourceSetAdapter.java:230)
    at org.sidiff.difference.technical.ResourceSetAdapter.init(ResourceSetAdapter.java:100)
    at org.sidiff.difference.technical.MergeImports.initResourceSetAdapter(MergeImports.java:197)
    at org.sidiff.difference.technical.MergeImports.merge(MergeImports.java:119)
    at org.sidiff.difference.lifting.facade.LiftingFacade.liftMeUp(LiftingFacade.java:111)
    at de.uni_stuttgart.iste.cowolf.evolution.AbstractEvolutionManager.evolve(AbstractEvolutionManager.java:95)
    at de.uni_stuttgart.iste.cowolf.ui.transformation.handler.Transform$1.run(Transform.java:134)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by renetrefft** [comment]
See also #496.
